name: 'Deploy'

on: push

permissions:
  id-token: write # Required for OIDC - see https://docs.npmjs.com/trusted-publishers
  contents: write # Required to create releases

jobs:
  version_check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_changed.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.3
      - name: Build application
        run: |
          cd packages/backend/
          bun run predeploy
      - name: Publish the script to Bunny
        uses: 'BunnyWay/actions/deploy-script@main'
        with:
          script_id: 61076
          file: 'packages/backend/dist/index.ts'
